### ISSUE TITLE
Offline-Related player issues

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [EssentialsX/Essentials#6277]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?bytebin=BnKtOvm3V0

### Error log (if applicable)

-

### Bug description

Since the changes to offline players in this dev build patch [Maintain strong reference for online users (](https://github.com/EssentialsX/Essentials/commit/302dd3fe35e0d49075266077acf8a412c48622b8)https://github.com/EssentialsX/Essentials/pull/6247[)](https://github.com/EssentialsX/Essentials/commit/302dd3fe35e0d49075266077acf8a412c48622b8) it seems to have broken many commands related to offline players.

I do use the latest available dev build at this point right now on paper 1.21.4. 

Before it used to just "work", but now things such as tpoffline, seen etc. just say the user never joined the server before.

### Steps to reproduce

Run paper 1.21.4
Run at least said dev build (since it happens on last currently too, just use that one?)
Join with a account, go off and use said commands on that account

### Expected behaviour

To output the right information

### Actual behaviour

Mentioned above.

### Additional Information

-

**Comment by saucylegs** [comment]
I noticed this issue the other day; I was trying to /tempban an offline user but it said it couldn't find them. Interestingly, when I ran the command from the server console instead of in-game, it worked just fine.

**Comment by CC-Odin** [comment]
also seeing this issue both in-game and on the console

**Comment by FellowNeighbour** [comment]
Likewise, this is happening on my server as well.

**Comment by JRoy** [comment]
@saucylegs @almecho @FellowNeighbour can you all run `/ess dump all` and send me the link?

**Comment by FellowNeighbour** [comment]
> [@saucylegs](https://github.com/saucylegs) [@almecho](https://github.com/almecho) [@FellowNeighbour](https://github.com/FellowNeighbour) can you all run `/ess dump all` and send me the link?

https://essentialsx.net/dump.html?bytebin=nAp1p1GoL3

**Comment by ZepsiZola** [comment]
I have this same issue.

https://essentialsx.net/dump.html?bytebin=bhf7ynW8CR

**Comment by forsakenliquid** [comment]
Same issue on my Server

**Comment by MODNMETL** [comment]
> [@saucylegs](https://github.com/saucylegs) [@almecho](https://github.com/almecho) [@FellowNeighbour](https://github.com/FellowNeighbour) can you all run `/ess dump all` and send me the link?

Yeah we're getting this on our 1.21.8 server, too. Here's our dump: https://essentialsx.net/dump.html?bytebin=RXl6NMs6UP

**Comment by NotYoWaifu** [comment]
Also having this issue and can't tpoffline to players offline
1.21.8 server
https://essentialsx.net/dump.html?bytebin=XvUIAMX1xM

**Comment by saucylegs** [comment]
> [@saucylegs](https://github.com/saucylegs) [@almecho](https://github.com/almecho) [@FellowNeighbour](https://github.com/FellowNeighbour) can you all run `/ess dump all` and send me the link?

@JRoy Here is a dump from shortly after restarting the server: https://essentialsx.net/dump.html?bytebin=A0gtfeeqXt

**Comment by GenOpenDiesel** [comment]
<img width="620" height="265" alt="Image" src="https://github.com/user-attachments/assets/b0043848-cf26-4cb6-9317-58c89f670755" />

YYEA I have the exact same issue. It shows incorrect data in /seen.

CoreProtect shows the player was there 10 days ago, but Essentials says it was a month ago.

Something is incorrectly validating the data.

For example, when the system was in offline mode and then moved to online mode, there are two profiles in Essentials.

<img width="517" height="27" alt="Image" src="https://github.com/user-attachments/assets/0af65346-a4e3-4cca-b5e7-07dd80b80c63" />

**Comment by Carter4242** [comment]
<img width="760" height="832" alt="Image" src="https://github.com/user-attachments/assets/1af4c695-a255-40fb-b7ee-485c0b862d9e" />

There is something extremely odd going on here. Also, {UNQIUE} is no longer correct.

Player 1 joins:
<img width="794" height="135" alt="Image" src="https://github.com/user-attachments/assets/1da3c534-deb3-40f2-95af-079277b7615d" />

Player 2 joins, but we've LOST 4 unique players????
<img width="785" height="132" alt="Image" src="https://github.com/user-attachments/assets/75511079-04a2-4630-91da-efc379fe06db" />

Both players joined one after each other, with player 2 joining second. I have to assume something to do with the online player count changing affected the number of unique players...
<img width="354" height="394" alt="Image" src="https://github.com/user-attachments/assets/2dc2976c-1ad0-42ab-961d-7fbc1b07bad1" />

**Comment by JRoy** [comment]
This should hopefully now be fixed in the latest dev build: https://next.essentialsx.net/downloads

Please let me know if this works for you guys!

PS: Thanks for your comment @Carter4242 who made me realize what the problem was.

**Comment by ILikeOrangeJuice** [comment]
Applied this build on all our test and live instances, used /seen on a user that has been off for approx an hour from now, still says user has never joined the server unfortunately.
Someone then, after applying the patches, joined our hub, where I used /seen username, which gave out the correct input, once the user went to another subserver and therefore offline, checking again, it says the user was never on the server.
https://prnt.sc/E54wgx4hWMiY

Edit - Another dump if that helps:
https://essentialsx.net/dump.html?bytebin=hu8Dk86zV6

**Comment by JRoy** [comment]
> Applied this build on all our test and live instances, used /seen on a user that has been off for approx an hour from now, still says user has never joined the server unfortunately. Someone then, after applying the patches, joined our hub, where I used /seen username, which gave out the correct input, once the user went to another subserver and therefore offline, checking again, it says the user was never on the server. [prnt.sc/E54wgx4hWMiY](https://prnt.sc/E54wgx4hWMiY)
> 
> Edit - Another dump if that helps: [essentialsx.net/dump.html?bytebin=hu8Dk86zV6](https://essentialsx.net/dump.html?bytebin=hu8Dk86zV6)

can you do the same kind of debug seen in this reply https://github.com/EssentialsX/Essentials/issues/6277#issuecomment-3254069647

for a few join/leaves do `/ess usermap cache` and share how the numbers look

**Comment by MODNMETL** [comment]
> can you do the same kind of debug seen in this reply [#6277 (comment)](https://github.com/EssentialsX/Essentials/issues/6277#issuecomment-3254069647)
> 
> for a few join/leaves do `/ess usermap cache` and share how the numbers look

We're still getting the same problem. This is our usermap cache, what else do you need?

<img width="681" height="38" alt="Image" src="https://github.com/user-attachments/assets/6f5df149-eb47-48cd-a006-7083fee583b1" />

**Comment by ILikeOrangeJuice** [comment]
Sorry I just read it now.
This is German, but I suppose the numbers are the important part, did it after our hub ran half a day with several joins/leaves.
https://prnt.sc/qltoKXbwiFq0

**Comment by FellowNeighbour** [comment]
Running the latest dev build and the issue still occurs.

**Comment by JRoy** [comment]
We have identified an issue with the fix I had originally made, the next dev build should finally resolve this.

Note that your usermap may be missing the name -> uuid mappings for some users that have yet to rejoin your server.

To rebuild the missing usermap mappings;

1. Stop your server
2. Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
3. In your `upgrades-done.yml` change `newUidCacheBuilt` to false
4. Start your server again.

you should notice all offline player functionality restored.

i apologize for the delay on these fixes and the issue to begin with.

**Comment by FellowNeighbour** [comment]
> We have identified an issue with the fix I had originally made, the next dev build should finally resolve this.
> 
> Note that your usermap may be missing the name -> uuid mappings for some users that have yet to rejoin your server.
> 
> To rebuild the missing usermap mappings;
> 
>     1. Stop your server
> 
>     2. Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
> 
>     3. In your `upgrades-done.yml` change `newUidCacheBuilt` to false
> 
>     4. Start your server again.
> 
> 
> you should notice all offline player functionality restored.
> 
> i apologize for the delay on these fixes and the issue to begin with.

This fixed the issue, thank you.

**Comment by forsakenliquid** [comment]
> We have identified an issue with the fix I had originally made, the next dev build should finally resolve this.
> 
> Note that your usermap may be missing the name -> uuid mappings for some users that have yet to rejoin your server.
> 
> To rebuild the missing usermap mappings;
> 
> 1. Stop your server
> 2. Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
> 3. In your `upgrades-done.yml` change `newUidCacheBuilt` to false
> 4. Start your server again.
> 
> you should notice all offline player functionality restored.
> 
> i apologize for the delay on these fixes and the issue to begin with.

did not get fixed on our Server with this.

<img width="678" height="92" alt="Image" src="https://github.com/user-attachments/assets/5244112b-b7bf-4bf4-92b5-7edf41e73742" />

this is what we have on our Server

**Comment by JRoy** [comment]
> > We have identified an issue with the fix I had originally made, the next dev build should finally resolve this.
> > 
> > Note that your usermap may be missing the name -> uuid mappings for some users that have yet to rejoin your server.
> > 
> > To rebuild the missing usermap mappings;
> > 
> > 1. Stop your server
> > 2. Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
> > 3. In your `upgrades-done.yml` change `newUidCacheBuilt` to false
> > 4. Start your server again.
> > 
> > you should notice all offline player functionality restored.
> > 
> > i apologize for the delay on these fixes and the issue to begin with.
> 
> did not get fixed on our Server with this.
> 
> <img width="678" height="92" alt="Image" src="https://github.com/user-attachments/assets/5244112b-b7bf-4bf4-92b5-7edf41e73742" />
> 
> this is what we have on our Server


need an /ess dump all

**Comment by forsakenliquid** [comment]
> > > We have identified an issue with the fix I had originally made, the next dev build should finally resolve this.
> > > Note that your usermap may be missing the name -> uuid mappings for some users that have yet to rejoin your server.
> > > To rebuild the missing usermap mappings;
> > > 
> > > 1. Stop your server
> > > 2. Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
> > > 3. In your `upgrades-done.yml` change `newUidCacheBuilt` to false
> > > 4. Start your server again.
> > > 
> > > you should notice all offline player functionality restored.
> > > i apologize for the delay on these fixes and the issue to begin with.
> > 
> > 
> > did not get fixed on our Server with this.
> > <img alt="Image" width="678" height="92" src="https://private-user-images.githubusercontent.com/151550029/487352764-5244112b-b7bf-4bf4-92b5-7edf41e73742.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0MzA5NjQsIm5iZiI6MTc1NzQzMDY2NCwicGF0aCI6Ii8xNTE1NTAwMjkvNDg3MzUyNzY0LTUyNDQxMTJiLWI3YmYtNGJmNC05MmI1LTdlZGY0MWU3Mzc0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwOVQxNTExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTkxOGYxNWI2Nzc5ZmJkYWJjZWY2MjYxOThhN2U2MjdlOGRjYjkxODBiNGI4YjFmODg3YWQzNGVkMjQ4YzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._NIsagyWxkaoASZvOx3iQ5GTDau1a01hnySc-iG8sI4">
> > this is what we have on our Server
> 
> need an /ess dump all

https://essentialsx.net/dump.html?bytebin=zyep4xFhPS

**Comment by JRoy** [comment]
>  https://essentialsx.net/dump.html?bytebin=zyep4xFhPS
> 

You ran the steps I listed with the server off? what commands are you running to determine that the commands aren't working with offline players?

**Comment by forsakenliquid** [comment]
> > https://essentialsx.net/dump.html?bytebin=zyep4xFhPS
> 
> You ran the steps I listed with the server off? what commands are you running to determine that the commands aren't working with offline players?

So I do these while the Server is offline?:

Stop your server
Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
In your upgrades-done.yml change newUidCacheBuilt to false
Start your server again.


We only used /seen and checked if its realy false by looking for coreprotect actions in that time

**Comment by JRoy** [comment]
> > > https://essentialsx.net/dump.html?bytebin=zyep4xFhPS
> > 
> > You ran the steps I listed with the server off? what commands are you running to determine that the commands aren't working with offline players?
> 
> So I do these while the Server is offline?:
> 
> Stop your server
> Backup existing usermap.bin and uuids.bin (you can just rename them to usermap.bin.bak and uuids.bin.bak if you want)
> In your upgrades-done.yml change newUidCacheBuilt to false
> Start your server again.
> 
> 
> We only used /seen and checked if its realy false by looking for coreprotect actions in that time
> 
> 

yes, that's step 1.
